spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springdemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  mvc:
    date-format: yyyy-MM-dd






