spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/trip?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: travel_Hikari #连接池名字，自己指定
      minimum-idle: 5 #连接池中最小的空闲连接数
      idle-timeout: 100000 #空闲连接最长存活时间
      maximum-pool-size: 30 #连接池中允许的最大连接数
      connection-timeout: 3000 #连接超时时间
  mvc:
    date-format: yyyy-MM-dd





